<#
.SYNOPSIS
    Publishes a Tin Roads build into this repo as an installable PWA.

.DESCRIPTION
    Takes the canonical single-file build from the private tin-roads repo,
    injects the PWA shell into its <head>, and writes index.html and sw.js.

    index.html and sw.js are GENERATED. Never edit them by hand — edit the
    build in the private repo and re-run this, or the next publish silently
    discards your change.

.EXAMPLE
    .\publish.ps1
    Picks the highest-versioned build from ..\Tin Roads and publishes it.

.EXAMPLE
    .\publish.ps1 -Push
    As above, then commits and pushes, which triggers the Pages deploy.
#>
[CmdletBinding()]
param(
    # The build to publish. Defaults to the highest-versioned build found in -SourceRepo.
    [string]$Source,
    # Where the canonical builds live.
    [string]$SourceRepo = (Join-Path (Split-Path $PSScriptRoot -Parent) "Tin Roads"),
    # Commit and push after generating.
    [switch]$Push
)

$ErrorActionPreference = "Stop"

# ---- locate the build -------------------------------------------------------
if (-not $Source) {
    $candidates = Get-ChildItem -Path $SourceRepo -Filter "tin_roads_empire_v*.html" -ErrorAction SilentlyContinue
    if (-not $candidates) {
        throw "No build found in '$SourceRepo'. Pass -Source explicitly."
    }
    # sort by real version order, not string order, so v0.10 beats v0.9
    $Source = ($candidates | Sort-Object {
        if ($_.Name -match 'v(\d+)\.(\d+)\.(\d+)') {
            [version]("{0}.{1}.{2}" -f $Matches[1], $Matches[2], $Matches[3])
        } else { [version]"0.0.0" }
    } | Select-Object -Last 1).FullName
}
if (-not (Test-Path $Source)) { throw "Build not found: $Source" }

$html = Get-Content $Source -Raw

if ($html -notmatch 'const\s+VERSION\s*=\s*"([^"]+)"') {
    throw "Could not read VERSION from $Source — has the build's version constant moved?"
}
$version = $Matches[1]

Write-Host "Source : $(Split-Path $Source -Leaf)"
Write-Host "Version: $version"

# ---- inject the PWA shell ---------------------------------------------------
# Status bar is opaque black rather than translucent: the game's layout is a
# fixed 100vh grid, so letting content slide under a notch would break it.
$shell = @"
<!-- PWA shell, injected by publish.ps1 — do not edit index.html by hand -->
<meta name="theme-color" content="#0B1E2D">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<meta name="apple-mobile-web-app-title" content="Tin Roads">
<link rel="manifest" href="manifest.webmanifest">
<link rel="apple-touch-icon" href="icons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="192x192" href="icons/icon-192.png">
<link rel="icon" type="image/png" sizes="512x512" href="icons/icon-512.png">
<script>
(function () {
  if ("serviceWorker" in navigator) {
    addEventListener("load", function () {
      navigator.serviceWorker.register("sw.js")["catch"](function () {});
    });
  }
  // Saves live in localStorage, which iOS will evict from an idle site.
  // Asking for persistence makes that much less likely.
  if (navigator.storage && navigator.storage.persist) {
    navigator.storage.persisted().then(function (already) {
      if (!already) { navigator.storage.persist(); }
    })["catch"](function () {});
  }
})();
</script>
"@

# Page zoom would fight the canvas's own pinch-zoom, so pin the scale.
$viewportNew = '<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">'
$htmlOut = [regex]::Replace($html, '<meta\s+name="viewport"[^>]*>', $viewportNew, 1)
if ($htmlOut -eq $html) { throw "Viewport meta not found — cannot inject PWA shell safely." }

$htmlOut = [regex]::Replace($htmlOut, [regex]::Escape($viewportNew), ($viewportNew + "`n" + $shell), 1)

$indexPath = Join-Path $PSScriptRoot "index.html"
[IO.File]::WriteAllText($indexPath, $htmlOut, (New-Object Text.UTF8Encoding($false)))

# ---- service worker, versioned so a new build actually lands ----------------
$sw = @"
/* Generated by publish.ps1 for Tin Roads v$version — do not edit by hand. */
const VERSION = "$version";
const CACHE = "tin-roads-" + VERSION;
const ASSETS = [
  "./",
  "./index.html",
  "./manifest.webmanifest",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon-maskable-512.png",
  "./icons/apple-touch-icon.png"
];

self.addEventListener("install", (e) => {
  e.waitUntil(
    caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;

  // The page itself is network-first, so a new build lands as soon as there is
  // a connection rather than waiting for a cache to expire. Cache is the
  // offline fallback.
  if (req.mode === "navigate") {
    e.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put("./index.html", copy));
          return res;
        })
        .catch(() => caches.match("./index.html"))
    );
    return;
  }

  // Everything else is versioned along with the cache, so cache-first is safe.
  e.respondWith(caches.match(req).then((hit) => hit || fetch(req)));
});
"@

$swPath = Join-Path $PSScriptRoot "sw.js"
[IO.File]::WriteAllText($swPath, $sw, (New-Object Text.UTF8Encoding($false)))

Write-Host "Wrote  : index.html ($([math]::Round((Get-Item $indexPath).Length / 1KB)) KB), sw.js"

if ($Push) {
    Push-Location $PSScriptRoot
    try {
        git add -A
        git commit -m "Publish v$version"
        git push
        Write-Host "Pushed. Pages will redeploy in a minute or so."
    } finally { Pop-Location }
} else {
    Write-Host "Not pushed. Re-run with -Push, or commit yourself."
}
